### PR TITLE
fix: Uncaught TypeError: Cannot read property '...' of undefined

### PR DESCRIPTION
**Pull request by clarkdo**

### CODE REVIEW

**Comment by pi0** [comment]
Ah thank you so much! I think it may be better making same PR on [original repo](https://github.com/framework7io/Framework7-Vue/tree/v2/kitchen-sink) too. As i'm keeping this repo in sync with that. (Not personally making PR to keep your credits on fixes)

**Comment by clarkdo** [comment]
welcome, I'll take a look at the original repo, many thanks for reminding.

**Comment by clarkdo** [comment]
It has been merged in  original repo https://github.com/framework7io/Framework7-Vue/pull/242, thanks :smile:

**Comment by pi0** [comment]
I've given you collaboration access too, in case wanted to make more contributions :) This repo will be moved into nuxt-community when was stable enough.

**Comment by clarkdo** [comment]
wow, it's my pleasure, will continue to make more contributions!

**Pull request merged**
